name: master build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Pull Localstack docker image
        run: docker pull localstack/localstack:latest
      - name: Pull DynamoDBLocal docker image
        run: docker pull amazon/dynamodb-local:latest
      - name: Pull Elasticsearch docker image
        run: docker pull docker.elastic.co/elasticsearch/elasticsearch:7.4.0
      - name: Build with Maven
        run: mvn -B --no-transfer-progress -DskipDocs=true install --file pom.xml
#      - name: Sonarcloud
#        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#      - name: Publish to GitHub Packages Apache Maven
#        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}